### ISSUE TITLE
Improve cmake_regenerate_on_save

### ISSUE THREAD

**Issue by hfn92** [Civitasv/cmake-tools.nvim#114] opened 2023-07-30 09:13 UTC
**Describe the problem or limitation you are having**
Currently `cmake_tools` only reacts to changes on `CMakeLists.txt` files. But changes the other files such as `.cmake` files or files used in `configure_file` can can cause cmake to re-generate.

**Describe the solution you'd like**
Fortunately `file_picker.get_cmake_files` should already contain all relevant files that can cause re-generation. Do you think it would be possible to also (or only) react to those files? It would have to be updated after each `cmake.generate()`

**Comment by Civitasv** [comment] 2023-07-30 09:24
Is it normal that users manually change contents of .cmake dir?

**Comment by hfn92** [comment] 2023-07-30 09:28
I don't mean the files in the cmake cache. But addidional cmake config files are usually `.cmake`. 
E.g `setting.cmake` and `coverage.cmake`. They are part of the source.

**Comment by Civitasv** [comment] 2023-07-30 09:30
Oh, I understand. Ideally, if they are included in CMakeLists.txt, we should register listener for them.

**Comment by Civitasv** [comment] 2023-07-30 12:46
I've confirmed that `.cmake` files that are included in CMakeLists.txt will be included in codemodel file.

**Comment by hfn92** [comment] 2023-07-30 13:04
It's not just `.cmake` files but also files used in `configure_file`. And probably some more. But the codemodel file should contain all those files

**Comment by hfn92** [comment] 2023-07-30 13:05
> Oh, I understand. Ideally, if they are included in CMakeLists.txt, we should register listener for them.
> 
> Follows are files or settings that should register contents change event in my opinion:
> 
> * `.cmake` files that are included in CMakeLists.txt
> * `presets` files
> * `variants` files (if presets not exists)
> * `kits` files (if presets not exists)
> * `CMakeSettings` (maybe)
> 
> @hfn92 What do you think?

I think its better to handle content change of each file in the cmake codemodel as those should include all relevant file.

**Comment by Civitasv** [comment] 2023-07-30 13:10
```lua
function cmake.create_regenerate_on_save_autocmd()
  local cmake_files = file_picker.get_cmake_files()

  -- for cmake files
  vim.api.nvim_create_autocmd("BufWritePre", {
    group = group,
    pattern = cmake_files,
    callback = function()
      local buf = vim.api.nvim_get_current_buf()
      -- Check if buffer is actually modified, and only if it is modified,
      -- execute the :CMakeGenerate, otherwise return. This is to avoid unnecessary regenerattion
      local buf_modified = vim.api.nvim_buf_get_option(buf, "modified")
      if buf_modified then
        cmake.generate({ bang = false, fargs = {} }, nil)
      end
    end,
  })
end
```

Do you think it is enough? We should re-register it every time after `CMakeGenerate`

**Comment by hfn92** [comment] 2023-07-30 13:19
I'm not sure. I don't know the vim api well enough. You can test it by adding
`configure_file(some_file ${CMAKE_BINARY_DIR}/some_file.junk)` to your CMakeLists.txt. Then changing `some_file` should trigger re-generate

**Comment by hfn92** [comment] 2023-07-30 13:22
regarding

```lua
pattern = { "CMakePresets.json", "CMakeUserPresets.json", "cmake-presets.json", "cmake-user-presets.json", "CMakeVariants.json", "CMakeVariants.yaml", "cmake-variants.yaml", "cmake-variants.json", "CMakeKits.json", "cmake-kits.json" }
```

I'm not sure if this works. I think once configured, changing files like `CMakePresets.json` doesn't affect the already created cmake cache. You'd need to delete cache first I think. So this is probably unnecessary.

**Comment by Civitasv** [comment] 2023-07-30 13:32
> configure_file(some_file ${CMAKE_BINARY_DIR}/some_file.junk)

It works! And turns out we don't need re-register it every time, it's dynamic.

**Comment by hfn92** [comment] 2023-07-30 13:34
> > configure_file(some_file ${CMAKE_BINARY_DIR}/some_file.junk)
> 
> It works! 
Great! :+1: 

> And turns out we don't need re-register it every time, it's dynamic.
I think we do. Because what happens if new files are added?

**Comment by Civitasv** [comment] 2023-07-30 13:59
```lua
function cmake.create_regenerate_on_save_autocmd()
  local cmake_files = file_picker.get_cmake_files()
  local others = { "CMakePresets.json", "CMakeUserPresets.json", "cmake-presets.json", "cmake-user-presets.json", "CMakeVariants.json", "CMakeVariants.yaml", "cmake-variants.yaml", "cmake-variants.json", "CMakeKits.json", "cmake-kits.json" }

  local pattern = {}
  for _, item in ipairs(cmake_files) do
    table.insert(pattern, vim.loop.cwd() .. "/" .. item)
  end

  for _, item in ipairs(others) do
    table.insert(pattern, vim.loop.cwd() .. "/" .. item)
  end

  if #pattern ~= 0 then
    -- for cmake files
    vim.api.nvim_create_autocmd("BufWritePre", {
      group = group,
      pattern = pattern,
      callback = function()
        print("FILE PICKER", vim.inspect(pattern))
        local buf = vim.api.nvim_get_current_buf()
        -- Check if buffer is actually modified, and only if it is modified,
        -- execute the :CMakeGenerate, otherwise return. This is to avoid unnecessary regenerattion
        local buf_modified = vim.api.nvim_buf_get_option(buf, "modified")
        if buf_modified then
          cmake.generate({ bang = false, fargs = {} }, nil)
        end
      end,
    })
  end
end
```

> I think we do. Because what happens if new files are added?

Yes, we should re-register every time after CMakeGenerate.

**Comment by Civitasv** [comment] 2023-07-30 14:01
>  I think once configured, changing files like CMakePresets.json doesn't affect the already created cmake cache. You'd need to delete cache first I think. So this is probably unnecessary.

Presets, variants, and kits have some configuration about cmake generation, they kinda like CMakeLists.txt, so I think it is necessary to watch them.

**Comment by hfn92** [comment] 2023-07-30 14:10
> > I think once configured, changing files like CMakePresets.json doesn't affect the already created cmake cache. You'd need to delete cache first I think. So this is probably unnecessary.
> 
> Presets, variants, and kits have some configuration about cmake generation, they kinda like CMakeLists.txt, so I think it is necessary to watch them.

ok, I see

**Closed** 2023-07-30 14:11 UTC
Labels: enhancement
