### ISSUE TITLE
CMakeRun not works on windows 

### ISSUE THREAD

**Issue by zuoxinyu** [Civitasv/cmake-tools.nvim#158] opened 2023-09-19 11:09 UTC
**Bug description**
I'm using windows 11 and powershell, `:CMakeRun` generates command like:
```
cmd /C "cd "C:/Users/username/workspace/project/build" && C:/Users/username/workspace/project/build\bin/myapp.exe"
```
which leads a syntax error.

**Steps to reproduce**

<details><summary>Minimal configuration</summary>

    require("cmake-tools").setup {
        cmake_command = "cmake",                                           -- this is used to specify cmake command path
        cmake_regenerate_on_save = true,                                   -- auto generate when save CMakeLists.txt
        cmake_generate_options = { "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" }, -- this will be passed when invoke `CMakeGenerate`
        cmake_build_options = {},                                          -- this will be passed when invoke `CMakeBuild`
        cmake_build_directory = "build",                                   -- this is used to specify generate directory for cmake
        cmake_build_directory_prefix = "cmake_build_",                     -- when cmake_build_directory is set to "", this option will be activated
        cmake_soft_link_compile_commands = true,                           -- this will automatically make a soft link from compile commands file to project root dir
        cmake_compile_commands_from_lsp = false,                           -- this will automatically set compile commands file location using lsp, to use it, please set `cmake_soft_link_compile_commands` to false
        cmake_kits_path = home .. '/.cmake-kits.json',                     -- this is used to specify global cmake kits path, see CMakeKits for detailed usage
        cmake_variants_message = {
            short = { show = true },                                       -- whether to show short message
            long = { show = true, max_length = 40 },                       -- whether to show long message
        },
        cmake_dap_configuration = {
            name = "cpp",
            type = "codelldb",
            request = "launch",
            stopOnEntry = false,
            runInTerminal = true,
            console = "integratedTerminal",
        },
    }

</details>

**Expected behavior**

`CMakeRun` executes selected binary correctly
**Screenshots**

**Environment**

- OS:  Windows 11
- Desktop environment:  powershell 7
- Plugins commit hash:  latest for now

**Additional context**
<!-- Add any other context about the problem here. --

**Comment by rohit-kumar-j** [comment] 2023-09-22 14:09
@zuoxinyu , if the issue is not yet fixed on master, you can use my branch temporarily as I use and support windows:

```lua
return { --lazy.nvim config
  "rohit-kumar-j/cmake-tools.nvim",
  branch = "master",
  config = function()
    require("cmake-tools").setup({
      -- Setup
    })
  end
}
```

or, you can use master on this commit: [`620ce8`](https://github.com/Civitasv/cmake-tools.nvim/commit/620ce8036337b320c6abb802df658916857191d9), as it is the latest commit I know of that is built and tested on windows.

```lua
return { --lazy.nvim config
  "Civitasv/cmake-tools.nvim",
  commit = "620ce8036337b320c6abb802df658916857191d9",
  config = function()
    require("cmake-tools").setup({
      -- Setup
    })
  end
}
```

**Comment by zuoxinyu** [comment] 2023-09-26 06:12
@rohit-kumar-j  oh, thanks for your branch!

**Comment by Civitasv** [comment] 2023-09-30 09:51
Can you fix it when you are free? @rohit-kumar-j

**Comment by rohit-kumar-j** [comment] 2023-10-01 19:57
I want to solve this keeping #151 and #145 in mind, so If it is okay, ,temporarily I will disable envScript from overseer.

**Comment by Civitasv** [comment] 2023-12-20 03:01
Closing it for now, feel free to open it if you still have this problem.

**Closed by Civitasv** 2023-12-20 03:01 UTC
Labels: bug
