### ISSUE TITLE
:CMakeDebug builds, then quits with no obvious reason

### ISSUE THREAD

**Issue by minego** [Civitasv/cmake-tools.nvim#191] opened 2024-01-12 16:45 UTC
**Bug description**
When trying to run `:CMakeDebug` to start debugging a target it properly asks for the target, etc, and then triggers a build if needed but then appears to quit without starting the debugger.

I don't see any obvious way to debug this to determine why it is failing.

**Steps to reproduce**

I am running a pretty basic setup of neovim with cmake-tools on Linux. I don't know why the debugger isn't working (It was previously, and broke at some point...) But, my bug isn't that it isn't working, but that cmake-tools doesn't provide any details about the failure.

**Expected behavior**
I'd like to see errors logged that I can view with `:messages`

**Screenshots**

**Environment**

- OS: Linux
- Desktop environment: N/A
- Plugins commit hash: [c59ac82](https://github.com/Civitasv/cmake-tools.nvim/commit/c59ac826f6dc2644ae82d0ede0aab65685d85ade)

**Additional context**

**Comment by Civitasv** [comment] 2024-01-20 12:27
We just invoke the `dap.run` function, if there exists errors, I think it will complain.
Can you provide more info? Such as a minimal project.

**Comment by Gerodote** [comment] 2024-04-04 09:21
I can confirm that `:CMakeDebug` works for me.

Try install dap-ui, then after `:CMakeDebug` failure, open dap ui `:lua require("dapui").open()`  . Usually there's a log of debugger that says the error that you have.

**Comment by Civitasv** [comment] 2024-05-03 14:40
Closing it for now, feel free to reopen it if you need further support.

**Closed by Civitasv** 2024-05-03 14:40 UTC
Labels: bug
